//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTask.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cours
    {
        private string title;

        public int Id { get; set; }

        [Required]
        [StringLength(20, MinimumLength = 4)]
        public string Title { get => title; set => title = value; }
        public double CreditHr { get; set; }
        public string Type { get; set; }
    }
}
